version: "3"
services:
  node-app:
    build:
      context: .
      args:
        - node_env=local
    volumes:
      - ./src:/app/src:ro
    environment:
      - node_env=local
    command: npm run start-dev