version: "3"
services:
  node-app:
    image: osamaaltamr/kube-ac
    env_file:
      - ./.env
    deploy: 
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on: 
      - postgres
      - redis

  # mongo:
  #   image: mongo
  #   restart: always
  #   volumes: 
  #     - mongo-db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   depends_on: 
  #     - mongo
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  redis:
    image: redis
  nginx:
    image: nginx
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80    
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - node-app   
  postgres:
    image: postgres
    restart: always
    volumes: 
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
volumes:
  mongo-db:
  postgres: