version: "3"
services:
  node-app:
    container_name: kube-doc
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    environment:
      - port=4000
      - node_env=local
      - host=data
    env_file:
      - ./.env